Update Test.yml

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -45,12 +45,10 @@ jobs:
   
       - name: Evaluate the model
         run: |
-          if ( $SCORE -gt 0.50 ) 
-          {
-            echo "Success: Score is greater than 0.50"
-            echo "{passed}={true}" >> $GITHUB_OUTPUT
-          } else {
-            echo "Failure: Score is not greater than 0.50"
-            echo "{passed}={false}" >> $GITHUB_OUTPUT
-            exit 1
-          }
+          if [[ $SCORE > 0.50 ]];
+          then
+            echo "Success: Score is greater than 0.50";
+          else
+            echo "Failure: Score is not greater than 0.50";
+            exit 1;
+          fi
